name: learing

on:
  push:
    branches:
      - main

jobs:
  basicrun:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup
        uses: actions/setup-node@v2
        with:
          nodeversion: 16.x
      - name: check github prop
        run: echo '${{ toJSON(github) }}'
      - name: check job prop
        run: echo '${{ toJSON(job)}}'
      - run: npm ci
      - run: echo Hello World



