name: learing

on:
  push:
    branches:
      -add-component

jobs:
  basicrun:
    runs-on: windows-latest
    steps:
      -uses: actions/checkout@v3
      -name: setup
       uses: actions/setup-node@v2
       with:
         nodeversion: 16.x
       run: npm ci
       run: echo Hello World



